### ISSUE TITLE
Support for Multi-Inputs Multi-outputs

### ISSUE THREAD

**Issue by deepgradient** [suinleelab/attributionpriors#2]
Dear team,
I am wondering whether this package support multi-inputs and multi-outputs in TF2? If yes, could you please provide an example as to how I should use the package?

**Comment by psturmfels** [comment]
Not sure why I haven't responded to this until now - the short answer is that it depends on what you mean by "multi-inputs" and "multi-outputs." When you run expected gradients, you have to run it with respect to a particular output index because it is only defined when run on a function that maps to a scalar. 

In terms of multi-inputs, you need to be able to take the derivative of your output with respect to your input for our package to work - so for the multi-input case, it's probably best to simply run our functions multiple times, one per each input and aggregate the penalty.
